Fourth task
annikoff/flashcards pull request #4
Opened 2016-12-09 21:05 UTC by annikoff

2016-12-11 18:54 UTC, davetoxa requested changes

2016-12-11 18:54 UTC, davetoxa commented on .travis.yml
> +    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
Зачем?

2016-12-11 18:54 UTC, davetoxa commented on .travis.yml
> +      - qtdeclarative5-dev
Зачем?

2016-12-11 18:54 UTC, davetoxa commented on .travis.yml
> +  - sleep 3
Зачем?)

2016-12-11 18:54 UTC, davetoxa commented on config/routes.rb
> +    end
А по проще endpoint сделать?

2016-12-11 19:00 UTC, annikoff commented on .travis.yml
> +    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
depreciation warning о том что с новой версией capybara-webkit нужно qt 5 использовать

2016-12-11 19:02 UTC, annikoff commented on .travis.yml
> +      - qtdeclarative5-dev
тоже, взял из репозитория capybara-webkit

2016-12-11 19:03 UTC, annikoff commented on .travis.yml
> +  - sleep 3
чтобы js тестировать при помощи capybara-webkit

2016-12-11 19:11 UTC, annikoff commented on config/routes.rb
> +    end
сделать короче путь?

2016-12-11 21:10 UTC, davetoxa commented
Да, было бы здорово
вс, 11 дек. 2016 г. в 22:11, Yakov <notifications@github.com>:

> *@annikoff* commented on this pull request.
>
>
>
>
> ------------------------------
>
>
>
>
> In config/routes.rb <https://github.com/annikoff/flashcards/pull/4>:
>
>
> > @@ -35,4 +35,12 @@
>
>      get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
>
>      put 'profile/:id' => 'profile#update', as: :profile
>
>    end
>
> +
>
> +  scope module: 'external' do
>
> +    resources :flickr, only: :photos_search do
>
> +      collection do
>
> +        get :photos_search
>
> +      end
>
> +    end
>
>
>
> сделать короче путь?
>
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/annikoff/flashcards/pull/4>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZeJbkHIZaQhOP1gh_4H4Zq8Gxgk3bpks5rHErIgaJpZM4LJW1U>
> .
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

2016-12-11 21:10 UTC, davetoxa commented
Это официальное решение?

вс, 11 дек. 2016 г. в 22:03, Yakov <notifications@github.com>:

> *@annikoff* commented on this pull request.
>
>
>
>
> ------------------------------
>
>
>
>
> In .travis.yml <https://github.com/annikoff/flashcards/pull/4>:
>
>
> >  before_script:
>
>    - cp config/database.yml.travis config/database.yml
>
>    - psql -c 'create database travis_ci_test;' -U postgres
>
>    - bundle exec rake db:migrate
>
> +  - export DISPLAY=:99.0
>
> +  - sh -e /etc/init.d/xvfb start
>
> +  - sleep 3
>
>
>
> чтобы js тестировать при помощи capybara-webkit
>
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/annikoff/flashcards/pull/4>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZeJU9d5PRcmCYHS_IAKNwt8mdMduTaks5rHEjygaJpZM4LJW1U>
> .
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

2016-12-12 06:09 UTC, annikoff commented on .travis.yml
> +  - sleep 3
Ага в доках тревиса так прописано https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

2016-12-13 18:47 UTC, merged